package View;

import Controller.AdminController;
import Model.AppointmentModel;
import Controller.PermissionController;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class admin extends javax.swing.JFrame {

    private String userCode;
    private AdminController controller;

    private List<String> currentPermissions;
    private int currentPage = 1;
    private int pageSize = 5;
    private int totalRecords = 0;

    public admin(String userCode) {
        this.userCode = userCode;
        this.controller = new AdminController(userCode);
        initComponents();
        loadAppointmentsByPage(currentPage);
        setLocationRelativeTo(null);
    }

    private void loadAppointmentsByPage(int page) {
        try {
            totalRecords = controller.getTotalAppointments();
            List<AppointmentModel> appointments = controller.getAppointmentsByPage(page, pageSize);

            DefaultTableModel model = (DefaultTableModel) display_lichhen.getModel();
            model.setRowCount(0); // Xoá dữ liệu cũ

            for (AppointmentModel appointment : appointments) {
                Object[] row = new Object[]{
                    appointment.getPatientCode(),
                    appointment.getAppointmentDate(),
                    appointment.getAppointmentTime(),
                    appointment.getSymptoms()
                };
                model.addRow(row);
            }

            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

            for (int i = 0; i < display_lichhen.getColumnCount(); i++) {
                display_lichhen.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi truy vấn lịch hẹn: " + ex.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_patient = new javax.swing.JButton();
        btn_medicine = new javax.swing.JButton();
        btn_appointment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_lichhen = new javax.swing.JTable();
        btn_mng_thuoc = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/benhvien.jpg"))); // NOI18N
        jLabel2.setFocusable(false);
        jLabel2.setInheritsPopupMenu(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 36));

        btn_logout.setBackground(new java.awt.Color(204, 0, 0));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 180, 60));

        btn_patient.setBackground(new java.awt.Color(0, 153, 255));
        btn_patient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_patient.setText("Quản lý bệnh nhân");
        btn_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_patientActionPerformed(evt);
            }
        });
        getContentPane().add(btn_patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, 60));

        btn_medicine.setBackground(new java.awt.Color(51, 153, 255));
        btn_medicine.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_medicine.setText("Quản lý đơn thuốc");
        btn_medicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_medicineActionPerformed(evt);
            }
        });
        getContentPane().add(btn_medicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, 60));

        btn_appointment.setBackground(new java.awt.Color(51, 153, 255));
        btn_appointment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_appointment.setText("Quản lý lịch hẹn");
        btn_appointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_appointmentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_appointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 60));

        display_lichhen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã bệnh nhân", "Ngày hẹn", "Giờ hẹn", "Triệu chứng"
            }
        ));
        jScrollPane1.setViewportView(display_lichhen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 620, 310));

        btn_mng_thuoc.setBackground(new java.awt.Color(51, 153, 255));
        btn_mng_thuoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_mng_thuoc.setText("Quản lý kho thuốc");
        btn_mng_thuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mng_thuocActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mng_thuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 180, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Lịch hẹn ");
        jPanel1.add(jLabel4);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 640, 400));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đăng xuất?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.setVisible(false); // Ẩn form hiện tại
            new login().setVisible(true); // Mở lại trang login
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_medicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_medicineActionPerformed
        CreateMedicinesView addForm = new CreateMedicinesView(this, userCode, userCode); 
        addForm.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btn_medicineActionPerformed

    private void btn_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_patientActionPerformed
        PatientView addForm = new PatientView(this, userCode, userCode); 
        addForm.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btn_patientActionPerformed

    private void btn_appointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_appointmentActionPerformed
        AppointmentView addForm = new AppointmentView(this, userCode, userCode); 
        addForm.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btn_appointmentActionPerformed

    private void btn_mng_thuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mng_thuocActionPerformed
        MedicinesView addForm = new MedicinesView(this, userCode, userCode); 
        addForm.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btn_mng_thuocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_appointment;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_medicine;
    private javax.swing.JButton btn_mng_thuoc;
    private javax.swing.JButton btn_patient;
    private javax.swing.JTable display_lichhen;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
