package View;

import Controller.PatientController;
import Model.PatientModel;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PatientView extends javax.swing.JFrame {

    private javax.swing.JFrame parent;
    private String userCode;
    private String userRole;
    private int currentPage = 1;
    private final int pageSize = 8;
    private PatientController controller;
    private int totalPatients = 0;

    public PatientView(javax.swing.JFrame parent, String userCode, String userRole) {
        this.parent = parent;
        this.userCode = userCode;
        this.userRole = userRole;
        this.controller = new PatientController();
        initComponents();
        loadPatients(currentPage);
        setLocationRelativeTo(null);
        loadTotalPatients();
        loadPatients(currentPage);
        updatePaginationButtons();
    }

    public void reloadCurrentPage() {
        loadPatients(currentPage);  
    }

    private void loadTotalPatients() {
        try {
            totalPatients = controller.getTotalPatients();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi đếm số bệnh nhân!");
        }
    }

    private void updatePaginationButtons() {
        int totalPages = (int) Math.ceil((double) totalPatients / pageSize);

        btn_frist.setEnabled(currentPage > 1);
        btn_back.setEnabled(currentPage > 1);

        btn_next.setEnabled(currentPage < totalPages);
        btn_last.setEnabled(currentPage < totalPages);
    }

    private void loadPatients(int page) {
        try {
            List<PatientModel> patients = controller.getPatientsByPage(page, pageSize);

            if (patients.isEmpty() && currentPage > 1) {
                currentPage--;
                JOptionPane.showMessageDialog(this, "Không còn dữ liệu để hiển thị.");
                loadPatients(currentPage);
                return;
            }

            // Lấy model của bảng và xóa dữ liệu cũ
            DefaultTableModel model = (DefaultTableModel) display_benhnhan.getModel();
            model.setRowCount(0); // clear existing rows

            // Thêm dữ liệu mới vào bảng
            for (PatientModel patient : patients) {
                Object[] rowData = {
                    patient.getPatientCode(),
                    patient.getFullName(),
                    patient.getDateOfBirth(),
                    patient.getGender(),
                    patient.getPhoneNumber()
                };
                model.addRow(rowData);
            }

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi lấy danh sách bệnh nhân: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_add1 = new javax.swing.JButton();
        btn_previous1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_search = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_viewhistory = new javax.swing.JButton();
        lb_benhnhan_code = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_benhnhan = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        btn_last = new javax.swing.JButton();
        btn_frist = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        btn_add1.setText("Thêm bệnh nhân");
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });

        btn_previous1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_previous1.setText("<");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_search.setBackground(new java.awt.Color(0, 153, 255));
        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_search.setText("Tìm kiếm");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel3.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, 40));

        btn_edit.setBackground(new java.awt.Color(0, 153, 255));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_edit.setText("Sửa bệnh nhân");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel3.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 150, 40));

        btn_delete.setBackground(new java.awt.Color(0, 153, 255));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_delete.setText("Xóa bệnh nhân");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel3.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 150, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Quản lý bệnh nhân");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        btn_back.setText("<");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel3.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        btn_next.setText(">");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        jPanel3.add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        btn_viewhistory.setBackground(new java.awt.Color(0, 153, 255));
        btn_viewhistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_viewhistory.setText("Lịch sử khám");
        btn_viewhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewhistoryActionPerformed(evt);
            }
        });
        jPanel3.add(btn_viewhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 150, 40));
        jPanel3.add(lb_benhnhan_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nhập thông tin bệnh nhân");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        display_benhnhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        display_benhnhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã BN", "Họ và tên", "Ngày sinh", "Giới tính", "SĐT"
            }
        ));
        jScrollPane1.setViewportView(display_benhnhan);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 610, 200));

        btn_add.setBackground(new java.awt.Color(0, 153, 255));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_add.setText("Thêm bệnh nhân");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel3.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 150, 40));

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 10, 90));

        btn_last.setText("Cuối");
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });
        jPanel3.add(btn_last, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        btn_frist.setText("Đầu");
        btn_frist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fristActionPerformed(evt);
            }
        });
        jPanel3.add(btn_frist, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed
        AddPatientView addForm = new AddPatientView(this, userCode, userRole);
        addForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_add1ActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        AddPatientView addForm = new AddPatientView(this, userCode, userRole);
        addForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        String input = lb_benhnhan_code.getText().trim();

        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã, tên hoặc số điện thoại bệnh nhân.");
            return;
        }

        try {
            List<PatientModel> patients = controller.searchPatients(input);

            if (patients.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy bệnh nhân phù hợp.");
                return;
            }

            // Lấy model của bảng và xóa dữ liệu cũ
            DefaultTableModel model = (DefaultTableModel) display_benhnhan.getModel();
            model.setRowCount(0); // clear existing rows

            // Thêm dữ liệu tìm được vào bảng
            for (PatientModel patient : patients) {
                Object[] rowData = {
                    patient.getPatientCode(),
                    patient.getFullName(),
                    patient.getDateOfBirth(),
                    patient.getGender(),
                    patient.getPhoneNumber()
                };
                model.addRow(rowData);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_viewhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewhistoryActionPerformed
        int selectedRow = display_benhnhan.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bệnh nhân để xem lịch sử.");
            return;
        }

        String patientCode = display_benhnhan.getValueAt(selectedRow, 0).toString();
        AppointmentDetailView detailView = new AppointmentDetailView(patientCode);
        detailView.setVisible(true);
    }//GEN-LAST:event_btn_viewhistoryActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int selectedRow = display_benhnhan.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bệnh nhân cần xóa trong bảng.");
            return;
        }

        // Lấy mã bệnh nhân từ dòng đã chọn
        String patientCode = display_benhnhan.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn xóa bệnh nhân có mã: " + patientCode + "?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                boolean deleted = controller.deletePatient(patientCode);
                if (deleted) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công.");
                    loadPatients(currentPage); // reload bảng
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại.");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        int selectedRow = display_benhnhan.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bệnh nhân cần sửa trong bảng.");
            return;
        }

        String patientCode = display_benhnhan.getValueAt(selectedRow, 0).toString();

        try {
            PatientModel patient = controller.getPatientByCode(patientCode);

            if (patient == null) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy bệnh nhân với mã: " + patientCode);
                return;
            }

            // Truyền tham chiếu form chính vào EditPatientView
            EditPatientView editForm = new EditPatientView(this, userCode, userRole, patient);
            editForm.setVisible(true);
            this.setVisible(false); // ẩn đi để sau sửa quay lại

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi lấy dữ liệu: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_fristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fristActionPerformed
        currentPage = 1;
        loadPatients(currentPage);
        updatePaginationButtons();
    }//GEN-LAST:event_btn_fristActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        if (currentPage > 1) {
            currentPage--;
            loadPatients(currentPage);
            updatePaginationButtons();
        }
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        int totalPages = (int) Math.ceil((double) totalPatients / pageSize);
        if (currentPage < totalPages) {
            currentPage++;
            loadPatients(currentPage);
            updatePaginationButtons();
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        currentPage = (int) Math.ceil((double) totalPatients / pageSize);
        loadPatients(currentPage);
        updatePaginationButtons();
    }//GEN-LAST:event_btn_lastActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose(); // Close the current add_benhnhan window
        if (parent != null) {
            parent.setVisible(true); // Show the parent window (benhnhan_manage)
        } else {
            // Fallback: Open a new benhnhan_manage window with userCode and userRole
            new PatientView(null, userCode, userRole).setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_add1;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_frist;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_previous1;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_viewhistory;
    private javax.swing.JTable display_benhnhan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lb_benhnhan_code;
    // End of variables declaration//GEN-END:variables
}
