package view.usersite;

import Controller.MemberController;
import controller.BorrowController;
import controller.BorrowDetailController;
import model.BooksModel;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.File;
import javax.swing.JOptionPane;
import model.MemberModel;

/**
 *
 * @author Vu Nguyen
 */
public class BookDetailView extends javax.swing.JFrame {

    /**
     * Creates new form BookDetailView
     */
    private BooksModel book;
    private String userCode;

    public BookDetailView(String userCode) {
        this.userCode = userCode;
        initComponents();
        setLocationRelativeTo(null);
    }

    public BookDetailView(BooksModel book, String userCode) {
        this.userCode = userCode;
        this.book = book;
        initComponents();
        setLocationRelativeTo(null); 
        showBookDetail();

        lbl_bookname.setText(book.getTitle());
        lbl_author.setText(book.getAuthor());
        lbl_date.setText(String.valueOf(book.getPublishYear()));
        lbl_category.setText(book.getCategory());

        if (book.getImageUrl() != null && !book.getImageUrl().isEmpty()) {
            File imageFile = new File(book.getImageUrl());
            if (imageFile.exists()) {
                ImageIcon icon = new ImageIcon(book.getImageUrl());
                Image scaledImage = icon.getImage().getScaledInstance(
                        lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                lblImage.setIcon(new ImageIcon(scaledImage));
            } else {
                lblImage.setText("Ảnh không tồn tại");
            }
        } else {
            lblImage.setText("Không có ảnh");
        }
    }

    private void showBookDetail() {
        if (book != null) {
            lbl_bookname.setText(book.getTitle());
            lbl_author.setText(book.getAuthor());
            lbl_date.setText(String.valueOf(book.getPublishYear()));
            lbl_category.setText(book.getCategory());

            String imagePath = book.getImageUrl(); // Đây là đường dẫn tuyệt đối
            System.out.println("Đường dẫn ảnh: " + imagePath);

            try {
                File imageFile = new File(imagePath);
                if (imageFile.exists()) {
                    ImageIcon icon = new ImageIcon(imageFile.getAbsolutePath());
                    Image scaledImage = icon.getImage().getScaledInstance(
                            lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                    lblImage.setIcon(new ImageIcon(scaledImage));
                } else {
                    lblImage.setText("Ảnh không tồn tại");
                }
            } catch (Exception e) {
                lblImage.setText("Lỗi ảnh");
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_bookname1 = new javax.swing.JTextField();
        lbl_bookname5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_bookname = new javax.swing.JTextField();
        lbl_author = new javax.swing.JTextField();
        lbl_date = new javax.swing.JTextField();
        lbl_category = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_borrow = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        dch_date = new com.toedter.calendar.JDateChooser();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book_1.png"))); // NOI18N
        jLabel1.setText("Thông tin sách");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 103, 221, 284));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên sách");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 88, 69, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tác giả");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 163, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Năm xuát bản");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 243, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Thể loại");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 323, 64, -1));
        getContentPane().add(lbl_bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 115, 236, 42));
        getContentPane().add(lbl_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 189, 236, 42));
        getContentPane().add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 269, 236, 42));
        getContentPane().add(lbl_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 349, 236, 42));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Ngày trả");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 409, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("*");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 409, 13, -1));

        btn_borrow.setBackground(new java.awt.Color(0, 153, 255));
        btn_borrow.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_borrow.setText("Mượn sách");
        btn_borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrowActionPerformed(evt);
            }
        });
        getContentPane().add(btn_borrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 441, 178, 62));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(dch_date, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(441, Short.MAX_VALUE)
                .addComponent(dch_date, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_borrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrowActionPerformed
        java.util.Date selectedDate = dch_date.getDate();
        java.util.Date now = new java.util.Date();

        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày trả sách.");
            return;
        }

        // Kiểm tra ngày trả có nằm trong quá khứ không
        if (!selectedDate.after(now)) {
            JOptionPane.showMessageDialog(this, "Ngày trả phải sau ngày hiện tại.");
            return;
        }

        try {
            // Lấy thông tin người mượn
            MemberController memberController = new MemberController();
            MemberModel member = memberController.getMemberByUserCode(userCode);

            if (member == null) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin hội viên.");
                return;
            }

            // Thêm vào bảng borrows
            BorrowController borrowController = new BorrowController();
            int borrowId = borrowController.createBorrow(member.getMemberId(),
                    new java.sql.Timestamp(now.getTime()),
                    new java.sql.Timestamp(selectedDate.getTime()));

            if (borrowId == -1) {
                JOptionPane.showMessageDialog(this, "Không thể mượn sách.");
                return;
            }

            // Thêm vào borrow_details và trừ sách
            BorrowDetailController detailController = new BorrowDetailController();
            boolean success = detailController.createBorrowDetail(borrowId, book.getBookId(), 1);

            if (!success) {
                JOptionPane.showMessageDialog(this, "Không đủ sách để mượn.");
                return;
            }

            JOptionPane.showMessageDialog(this, "Mượn sách thành công.");
            this.dispose(); // đóng cửa sổ sau khi mượn

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi mượn sách.");
        }
    }//GEN-LAST:event_btn_borrowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrow;
    private com.toedter.calendar.JDateChooser dch_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField lbl_author;
    private javax.swing.JTextField lbl_bookname;
    private javax.swing.JTextField lbl_bookname1;
    private javax.swing.JTextField lbl_bookname5;
    private javax.swing.JTextField lbl_category;
    private javax.swing.JTextField lbl_date;
    // End of variables declaration//GEN-END:variables
}
