package view.adminsite;

import Controller.BookImportController;
import Controller.BooksController;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.BookImportDetailModel;
import model.BookImportModel;
import model.BooksModel;
import view.LoginView;

/**
 *
 * @author Vu Nguyen
 */
public class BookImportView extends javax.swing.JFrame {

    private int currentPage = 1;
    private int pageSize = 10;
    private int totalPages = 1;

    /**
     * Creates new form BookImportView
     */
    public BookImportView() {
        initComponents();
        loadBookTable();
        setLocationRelativeTo(null);
    }

    private void loadBookTable() {
        try {
            BooksController controller = new BooksController();
            List<BooksModel> books = controller.getBooksByPageImp(currentPage, pageSize);
            int totalBooks = controller.getTotalBookCount();
            totalPages = (int) Math.ceil((double) totalBooks / pageSize);

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new Object[]{"STT", "Tên sách", "Thể loại", "Số lượng"});

            int stt = (currentPage - 1) * pageSize + 1;
            for (BooksModel book : books) {
                model.addRow(new Object[]{
                    stt++,
                    book.getTitle(),
                    book.getCategory(),
                    book.getQuantity()
                });
            }

            display_bookList.setModel(model);

            // Căn giữa bảng
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            for (int i = 0; i < display_bookList.getColumnCount(); i++) {
                display_bookList.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }

            // Vô hiệu hóa nút nếu ở đầu/cuối
            btn_first.setEnabled(currentPage > 1);
            btn_back.setEnabled(currentPage > 1);
            btn_next.setEnabled(currentPage < totalPages);
            btn_last.setEnabled(currentPage < totalPages);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu sách: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        btn_customMng = new javax.swing.JButton();
        btn_bookmng = new javax.swing.JButton();
        btn_sachMuon = new javax.swing.JButton();
        btn_dntBook = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_bookList = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btn_first = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        btn_bookImport = new javax.swing.JButton();
        lbl_quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_importDetail = new javax.swing.JButton();
        btn_addBook = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book.png"))); // NOI18N
        jLabel2.setText("Xin chào Admin");

        btn_menu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_menu.setText("Trang chủ");
        btn_menu.setToolTipText("");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_customMng.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_customMng.setText("Khách hàng");
        btn_customMng.setMaximumSize(new java.awt.Dimension(176, 43));
        btn_customMng.setMinimumSize(new java.awt.Dimension(176, 43));
        btn_customMng.setPreferredSize(new java.awt.Dimension(176, 43));
        btn_customMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customMngActionPerformed(evt);
            }
        });

        btn_bookmng.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_bookmng.setText("Thư viện");
        btn_bookmng.setMaximumSize(new java.awt.Dimension(176, 43));
        btn_bookmng.setMinimumSize(new java.awt.Dimension(176, 43));
        btn_bookmng.setPreferredSize(new java.awt.Dimension(176, 43));
        btn_bookmng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookmngActionPerformed(evt);
            }
        });

        btn_sachMuon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_sachMuon.setText("Mượn sách");
        btn_sachMuon.setMaximumSize(new java.awt.Dimension(176, 43));
        btn_sachMuon.setMinimumSize(new java.awt.Dimension(176, 43));
        btn_sachMuon.setPreferredSize(new java.awt.Dimension(176, 43));
        btn_sachMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sachMuonActionPerformed(evt);
            }
        });

        btn_dntBook.setBackground(new java.awt.Color(0, 153, 255));
        btn_dntBook.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_dntBook.setText("Nhập sách");
        btn_dntBook.setMaximumSize(new java.awt.Dimension(176, 43));
        btn_dntBook.setMinimumSize(new java.awt.Dimension(176, 43));
        btn_dntBook.setPreferredSize(new java.awt.Dimension(176, 43));
        btn_dntBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dntBookActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(255, 102, 102));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_logout.setText("Đăng xuất");
        btn_logout.setMaximumSize(new java.awt.Dimension(176, 43));
        btn_logout.setMinimumSize(new java.awt.Dimension(176, 43));
        btn_logout.setPreferredSize(new java.awt.Dimension(176, 43));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 14, Short.MAX_VALUE))
            .addComponent(btn_customMng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_bookmng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_sachMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_dntBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_customMng, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_bookmng, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sachMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_dntBook, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 600));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ddd.png"))); // NOI18N
        jLabel3.setText("Nhập thêm sách vào kho");

        display_bookList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        display_bookList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Tên sách", "Thẻ loại", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(display_bookList);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Danh sách sách trong thư viện ");

        btn_first.setText("Đầu");
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        btn_back.setText("<");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_next.setText(">");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_last.setText("Cuối");
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        btn_bookImport.setBackground(new java.awt.Color(0, 153, 255));
        btn_bookImport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_bookImport.setText("Nhập thêm sách ");
        btn_bookImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookImportActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Nhập số lượng sách");

        btn_importDetail.setBackground(new java.awt.Color(0, 153, 255));
        btn_importDetail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_importDetail.setText("Lịch sử nhập sách");
        btn_importDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importDetailActionPerformed(evt);
            }
        });

        btn_addBook.setBackground(new java.awt.Color(0, 153, 255));
        btn_addBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_addBook.setText("Thêm sách");
        btn_addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4)
                                .addGap(261, 261, 261))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_quantity)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5))
                            .addComponent(btn_bookImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_addBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_importDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_first)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_next)
                .addGap(18, 18, 18)
                .addComponent(btn_last)
                .addGap(274, 274, 274))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_addBook, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_importDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_bookImport, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_last)
                    .addComponent(btn_next)
                    .addComponent(btn_back)
                    .addComponent(btn_first))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 810, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ảnh nền.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 870, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_customMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customMngActionPerformed
        new MemberView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_customMngActionPerformed

    private void btn_bookmngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookmngActionPerformed
        new MngBookView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_bookmngActionPerformed

    private void btn_sachMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sachMuonActionPerformed
        new MngBorrowView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_sachMuonActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn đăng xuất không?",
                "Xác nhận đăng xuất",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            new LoginView().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_importDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importDetailActionPerformed
        new ImportDetailView().setVisible(true);

    }//GEN-LAST:event_btn_importDetailActionPerformed

    private void btn_bookImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookImportActionPerformed
        try {
            int selectedRow = display_bookList.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Hãy chọn sách để nhập.");
                return;
            }

            // Lấy danh sách sách của trang hiện tại
            BooksController bookController = new BooksController();
            List<BooksModel> books = bookController.getBooksByPageImp(currentPage, pageSize);

            // Kiểm tra nếu selectedRow vượt quá danh sách
            if (selectedRow >= books.size()) {
                JOptionPane.showMessageDialog(this, "Dữ liệu sách không hợp lệ.");
                return;
            }

            BooksModel selectedBook = books.get(selectedRow);
            int bookId = selectedBook.getBookId();

            // Kiểm tra số lượng nhập vào
            String quantityStr = lbl_quantity.getText().trim();
            if (quantityStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng sách.");
                return;
            }

            int quantity = Integer.parseInt(quantityStr);
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0.");
                return;
            }

            // Kiểm tra sách có tồn tại trong CSDL không
            BooksModel bookInDB = bookController.getBookById(bookId);
            if (bookInDB == null) {
                JOptionPane.showMessageDialog(this, "Sách không tồn tại trong cơ sở dữ liệu.");
                return;
            }

            // Tiến hành nhập sách
            BookImportController importController = new BookImportController();
            BookImportModel importModel = new BookImportModel(new java.util.Date(), 1); // Giả sử member_id = 1
            int importId = importController.createBookImport(importModel);

            // Tạo chi tiết nhập
            BookImportDetailModel detailModel = new BookImportDetailModel(importId, bookId, quantity);
            importController.addBookImportDetail(detailModel);

            // Cập nhật số lượng sách
            importController.updateBookStock(bookId, quantity);

            JOptionPane.showMessageDialog(this, "Nhập sách thành công!");
            loadBookTable();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng nhập phải là số nguyên hợp lệ.");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi nhập sách: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_bookImportActionPerformed

    private void btn_dntBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dntBookActionPerformed
        new BookImportView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_dntBookActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        currentPage = 1;
        loadBookTable();
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        if (currentPage > 1) {
            currentPage--;
            loadBookTable();
        }
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        if (currentPage < totalPages) {
            currentPage++;
            loadBookTable();
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        currentPage = totalPages;
        loadBookTable();
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        new AdminView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addBookActionPerformed
        new AddBookView().setVisible(true);
    }//GEN-LAST:event_btn_addBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookImportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookImportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookImportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookImportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookImportView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addBook;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_bookImport;
    private javax.swing.JButton btn_bookmng;
    private javax.swing.JButton btn_customMng;
    private javax.swing.JButton btn_dntBook;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_importDetail;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_sachMuon;
    private javax.swing.JTable display_bookList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lbl_quantity;
    // End of variables declaration//GEN-END:variables
}
