package view.adminsite;

/**
 *
 * @author Vu Nguyen
 */
import controller.BorrowDetailController;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BorrowDetailModel;
import view.LoginView;

public class MngBorrowView extends javax.swing.JFrame {

    private int currentPage = 1;
    private int itemsPerPage = 10;
    private int totalPages = 1;
    private List<BorrowDetailModel> allBorrowList;

    /**
     * Creates new form MngBorrowView
     */
    public MngBorrowView() {
        initComponents();
        setLocationRelativeTo(null);
        BorrowDetailController controller = new BorrowDetailController();
        allBorrowList = controller.getAllBorrowing();
        updatePagination();
    }

    private void loadBorrowedBooks(List<BorrowDetailModel> list) {
        // ⚠️ Gọi xử lý phạt trước khi hiển thị
        BorrowDetailController controller = new BorrowDetailController();
        controller.checkAndInsertPenalties();  // ← gọi ở đây để đảm bảo dữ liệu đã có trong DB

        DefaultTableModel model = (DefaultTableModel) display_borrow.getModel();
        model.setRowCount(0);
        int stt = 1;

        // Định dạng ngày
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        for (BorrowDetailModel b : list) {
            String expectedReturn = b.getExpectedReturnDate() != null ? dateFormat.format(b.getExpectedReturnDate()) : "";
            String actualReturn = b.getActualReturnDate() != null ? dateFormat.format(b.getActualReturnDate()) : "Chưa trả";

            model.addRow(new Object[]{
                stt++,
                b.getMemberName(),
                b.getBookTitle(),
                expectedReturn,
                actualReturn,
                b.getLateFee()
            });
        }
    }

    private void updatePagination() {
        int totalItems = allBorrowList.size();
        totalPages = (int) Math.ceil((double) totalItems / itemsPerPage);

        // Giới hạn trang
        if (currentPage > totalPages) {
            currentPage = totalPages;
        }
        if (currentPage < 1) {
            currentPage = 1;
        }

        int start = (currentPage - 1) * itemsPerPage;
        int end = Math.min(start + itemsPerPage, totalItems);

        List<BorrowDetailModel> currentPageList = allBorrowList.subList(start, end);
        loadBorrowedBooks(currentPageList);
        updateButtonState();
    }

    private void updateButtonState() {
        btn_first1.setEnabled(currentPage > 1);
        btn_back1.setEnabled(currentPage > 1);
        btn_next1.setEnabled(currentPage < totalPages);
        btn_last1.setEnabled(currentPage < totalPages);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        btn_customMng = new javax.swing.JButton();
        btn_bookmng = new javax.swing.JButton();
        btn_sachMuon = new javax.swing.JButton();
        btn_dntBook = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_first1 = new javax.swing.JButton();
        btn_back1 = new javax.swing.JButton();
        btn_next1 = new javax.swing.JButton();
        btn_last1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_borrow = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lbl_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_feeRule = new javax.swing.JButton();
        btn_check = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book.png"))); // NOI18N
        jLabel2.setText("Xin chào Admin");

        btn_menu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_menu.setText("Trang chủ");
        btn_menu.setToolTipText("");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_customMng.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_customMng.setText("Khách hàng");
        btn_customMng.setMaximumSize(new java.awt.Dimension(176, 43));
        btn_customMng.setMinimumSize(new java.awt.Dimension(176, 43));
        btn_customMng.setPreferredSize(new java.awt.Dimension(176, 43));
        btn_customMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customMngActionPerformed(evt);
            }
        });

        btn_bookmng.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_bookmng.setText("Thư viện");
        btn_bookmng.setMaximumSize(new java.awt.Dimension(176, 43));
        btn_bookmng.setMinimumSize(new java.awt.Dimension(176, 43));
        btn_bookmng.setPreferredSize(new java.awt.Dimension(176, 43));
        btn_bookmng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookmngActionPerformed(evt);
            }
        });

        btn_sachMuon.setBackground(new java.awt.Color(0, 153, 255));
        btn_sachMuon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_sachMuon.setText("Mượn sách");
        btn_sachMuon.setMaximumSize(new java.awt.Dimension(176, 43));
        btn_sachMuon.setMinimumSize(new java.awt.Dimension(176, 43));
        btn_sachMuon.setPreferredSize(new java.awt.Dimension(176, 43));
        btn_sachMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sachMuonActionPerformed(evt);
            }
        });

        btn_dntBook.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_dntBook.setText("Nhập sách");
        btn_dntBook.setMaximumSize(new java.awt.Dimension(176, 43));
        btn_dntBook.setMinimumSize(new java.awt.Dimension(176, 43));
        btn_dntBook.setPreferredSize(new java.awt.Dimension(176, 43));
        btn_dntBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dntBookActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(255, 102, 102));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_logout.setText("Đăng xuất");
        btn_logout.setMaximumSize(new java.awt.Dimension(176, 43));
        btn_logout.setMinimumSize(new java.awt.Dimension(176, 43));
        btn_logout.setPreferredSize(new java.awt.Dimension(176, 43));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 14, Short.MAX_VALUE))
            .addComponent(btn_customMng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_bookmng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_sachMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_dntBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_customMng, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_bookmng, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sachMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_dntBook, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 600));

        btn_first1.setText("Đầu");
        btn_first1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_first1ActionPerformed(evt);
            }
        });

        btn_back1.setText("<");
        btn_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back1ActionPerformed(evt);
            }
        });

        btn_next1.setText(">");
        btn_next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_next1ActionPerformed(evt);
            }
        });

        btn_last1.setText("Cuối");
        btn_last1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_last1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reader-1713700-1453871.png"))); // NOI18N
        jLabel4.setText("Quản lý sách đang mượn");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Sách đang mượn");

        display_borrow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        display_borrow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Người dùng", "Tên sách", "Dự kiến trả", "Thời gian trả", "Phạt trả muộn"
            }
        ));
        jScrollPane1.setViewportView(display_borrow);
        if (display_borrow.getColumnModel().getColumnCount() > 0) {
            display_borrow.getColumnModel().getColumn(0).setMinWidth(50);
            display_borrow.getColumnModel().getColumn(0).setPreferredWidth(50);
            display_borrow.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-512 (1).png"))); // NOI18N
        jLabel5.setText("Tìm theo tên người dùng");

        btn_search.setBackground(new java.awt.Color(0, 153, 255));
        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_search.setText("Tìm kiếm");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_feeRule.setBackground(new java.awt.Color(0, 153, 255));
        btn_feeRule.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_feeRule.setText("Điều chỉnh phí phạt");
        btn_feeRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_feeRuleActionPerformed(evt);
            }
        });

        btn_check.setBackground(new java.awt.Color(0, 153, 255));
        btn_check.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_check.setText("Kiểm tra trả muộn");
        btn_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btn_first1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_back1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_last1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addGap(261, 261, 261)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_search, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_feeRule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btn_check, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_feeRule, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_search)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_last1)
                    .addComponent(btn_next1)
                    .addComponent(btn_back1)
                    .addComponent(btn_first1))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 830, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ảnh nền.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 870, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_customMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customMngActionPerformed
        new MemberView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_customMngActionPerformed

    private void btn_bookmngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookmngActionPerformed
        new MngBookView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_bookmngActionPerformed

    private void btn_sachMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sachMuonActionPerformed
        new MngBorrowView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_sachMuonActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn đăng xuất không?",
                "Xác nhận đăng xuất",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            new LoginView().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_dntBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dntBookActionPerformed
        new BookImportView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_dntBookActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        new AdminView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        String keyword = lbl_search.getText().trim();
        BorrowDetailController controller = new BorrowDetailController();

        if (keyword.isEmpty()) {
            allBorrowList = controller.getAllBorrowing();
        } else {
            allBorrowList = controller.searchBorrowing(keyword);
        }

        currentPage = 1;
        updatePagination();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_feeRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_feeRuleActionPerformed
        new LateFeeRuleView().setVisible(true);
    }//GEN-LAST:event_btn_feeRuleActionPerformed

    private void btn_first1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_first1ActionPerformed
        currentPage = 1;
        updatePagination();
    }//GEN-LAST:event_btn_first1ActionPerformed

    private void btn_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back1ActionPerformed
        if (currentPage > 1) {
            currentPage--;
            updatePagination();
        }
    }//GEN-LAST:event_btn_back1ActionPerformed

    private void btn_next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_next1ActionPerformed
        if (currentPage < totalPages) {
            currentPage++;
            updatePagination();
        }
    }//GEN-LAST:event_btn_next1ActionPerformed

    private void btn_last1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_last1ActionPerformed
        currentPage = totalPages;
        updatePagination();
    }//GEN-LAST:event_btn_last1ActionPerformed

    private void btn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkActionPerformed
        BorrowDetailController controller = new BorrowDetailController();
        controller.checkAndInsertPenalties(); // Gọi xử lý phạt

        // Tải lại dữ liệu mới sau khi phạt (cập nhật DB)
        allBorrowList = controller.getAllBorrowing();
        currentPage = 1;
        updatePagination();

        JOptionPane.showMessageDialog(this, "Đã kiểm tra và cập nhật các bản ghi trả muộn.");
    }//GEN-LAST:event_btn_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MngBorrowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MngBorrowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MngBorrowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MngBorrowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MngBorrowView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back1;
    private javax.swing.JButton btn_bookmng;
    private javax.swing.JButton btn_check;
    private javax.swing.JButton btn_customMng;
    private javax.swing.JButton btn_dntBook;
    private javax.swing.JButton btn_feeRule;
    private javax.swing.JButton btn_first1;
    private javax.swing.JButton btn_last1;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_next1;
    private javax.swing.JButton btn_sachMuon;
    private javax.swing.JButton btn_search;
    private javax.swing.JTable display_borrow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lbl_search;
    // End of variables declaration//GEN-END:variables
}
